### ISSUE TITLE
Stock on hand information is not updated on the bar chart on the home page after an activity (eg dispense or receive), you have to exit the app and come back for the bar chart and soh to be updated. Maybe we include an update button on the menu bar to do this instead of having to exit the app after every activity

### ISSUE THREAD

**Issue by chai-lmis** [chailmis/chailmis-android#172]

**Comment by jobasiimwe** [comment]
This works fine in the Latest APK. If you use the back button of the tablet, the SOH will not be updated because the tablets back button removes the current activity and loads the previous activity.
But if you hit the App's home icon (the app logo) it reloads the home activity and redraws the graph and the new SOH appears immediately.

**Comment by chai-lmis** [comment]
ok, this works using the home icon - please include in documentation

**Comment by cvaldez519** [comment]
TESTED. I did this with dispense, receive, and losses, which requires user navigation back to the homepage the chart was updated. Did it using adjustment reason "physical count"  which automatically redirects to home page, also updated.
